### PR TITLE
Refactor coordinates conversion

### PR DESCRIPTION
**Pull request by santisoler**
Geographic coordinates conversion functions now get the full coordinates
as arguments rather than only the `latitude` and `radius`/`height`, and returns
the full set of converted coordinates.
The previous implementation was inconvenient for real applications.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

### CODE REVIEW

**Comment by leouieda** [comment]
@santisoler just noticed that if we want these functions to work with Verde gridders, they should actually take `longitude, latitude, height` instead of `coordinates`: https://github.com/fatiando/verde/blob/master/verde/base/base_classes.py#L294

For example, if we make a spherical equivalent layer using Verde, we could use these functions to generate geodetic grids easily by passing them in as the `projection` argument to the `grid` method.

I don't think it's too inconvenient since the user code would change from `geodetic_to_spherical(coordinates)` to `geodetic_to_spherical(*coordinates)`.

**Comment by santisoler** [comment]
I'm a little bit confused about your proposal.

> just noticed that if we want these functions to work with Verde gridders

On what cases you want Verde gridders to convert from spherical to geodetic or from geodetic to spherical?
Maybe I'm missing an obvious example for that...

The `coordinates` tuple on the line you linked is expected to have only `longitude`, `latitude` coordinates, not `longitude`, `latitude`, `height`. Remeber that the `height`/`radius` array is crucial for the spherical to geodetic conversion. I feel I'm missing something around this...

**Comment by leouieda** [comment]
The use case I had in mind what something like this:

```python
# Load observed gravity in geodetic coordinates
lon, lat, height, gravity = np.loadtxt(...)

# Convert to geocentric spherical so we can use a spherical gridder
coordinates = hm.geodetic_to_spherical((lon, lat, height))

# Grid using equivalent sources in spherical coordinates
eql = hm.EQLHarmonic(kernel="spherical", ...)
eql.fit(coordinates, gravity)

# Generate a geodetic grid using our spherical gridder
grid = eql.grid(region=(...), spacing=0.1, extra_coords=[1000],
                projection=hm.spherical_to_geodetic)
# extra_coords is the ellipsoidal height of the grid
```

In this case, we can use a spherical gridder to generate a geodetic grid without much effort. This is the same way we can make geodetic grids from Cartesian gridders in Verde.

The expectation of `coordinates=(latitude, longitude)` is only in the docstring. The code itself doesn't care as long as the number of coordinates `projection` accepts is the same as the number `grid_coordinates` returns. Using `extra_coords` will make it return 3 instead of 2.

**Comment by santisoler** [comment]
Thanks for that example @leouieda.
Now I understand what you meant.
I agree and just made those changes.
I think it's ready to be merged.

**Pull request merged**
