### PR TITLE
Move configuration from setup.py to setup.cfg

### PR DESCRIPTION
**Pull request by leouieda**
Make the move away from setup.py following the recommendations from the
Python packaging guides. Moves the requirement listing to setup.cfg as
well and will use a script to extract this for conda installing on CI.

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
Linting error is fixed in #295

**Comment by leouieda** [comment]
Done!

Should I update the style checking workflow to match this? https://github.com/fatiando/pooch/blob/main/.github/workflows/style.yml  

Basically concentrate on a "format" and a "style" run, that way if format fails we know that the solution is "run make format" (no matter why it failed).

Otherwise, this is only held back by the linting false-positive.

**Comment by leouieda** [comment]
Also applies https://github.com/fatiando/community/issues/42

**Review by santisoler — APPROVED** [review]
Looking great! After long time, I'm merging this.

**Pull request merged**
