### PR TITLE
Keep metadata of sample datasets in the xarray objects

### LINKED ISSUE #125: Missing attributes on ICGEM datasets
**Description of the problem**

We currently have three sample datasets that have been downloaded from the [ICGEM Calculation Service](http://icgem.gfz-potsdam.de/calcgrid):
- Earth Topography
- Earth Gravity
- Earth Geoid

Each dataset can be fetched through its own function. Every one of these functions claims to have more details regarding the generation of the grid under the `attrs` attribute of the `Dataset`.
The problem is neither of the returned `Dataset`s have non empty `attrs`.

Would be nice to correct this and include the attributes related to the grid generation.
I think these grids where generated by @leouieda, so maybe he has more idea of what information should be included on the `attrs`.

Just by naming some possible attributes that appear on the ICGEM Calculation Service:
- Reference ellipsoid
- Height above the ellipsoid
- Grid step
- Model used (for gravity and geoid)
- Tide system
- Zero degree term (yes/no)
- Gaussian filter and filter length
- Low-pass filtering
    - Start gentle cut
    - Maximum degree

### PR DESCRIPTION
**Pull request by nshea3**
Fixes #125 

Many global attributes are included in the netcdf files, however they are dropped in the `fetch_*` functions in `sample_data.py` with the float64 cast: `data = xr.open_dataset(fname, engine="scipy").astype("float64")`.  This is a known issue in xarray (https://github.com/pydata/xarray/issues/2049) and the current solution is to open the NetCDF file as-is, cast to the new datatype, and then copy the global attributes to the new object.

Also added tests to `test_sample_data.py` to check that the `attrs` attribute is not an empty dictionary. 

**Reminders**:

- [x] Run `make format` and `make check` to make sure the code follows the style guide.
- [x] Add tests for new features or tests that would have caught the bug that you're fixing.
- [x] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [x] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [x] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [x] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by santisoler** [comment]
Since we are about to move all datasets to Rockhound (see #179), we should remember to apply the same changes we perform here on https://github.com/fatiando/rockhound/pull/84.

**Comment by nshea3** [comment]
Excellent point thank you @santisoler I will make that change so we avoid duplicating the xarray.

I'll add a test for the `refsysname` attribute as well. Are there any others I should include?

**Comment by santisoler** [comment]
> I'll add a test for the refsysname attribute as well. Are there any others I should include?

Maybe we can add those attributes of which the data depends on.
For example, the `refsysname` is crucial because it sets the reference frame (and which normal gravity was removed if we are requesting for gravity anomalies or disturbances).
I would also test the `modelname`, the `max_used_degree` and probably the `tide_system`.
Another things we might want to test if the min and maximum values agree with the ones that are hardcoded in the `tests/sample_data.py`:

https://github.com/fatiando/harmonica/blob/2980071fce37948f2d13d8b7120c96ed18923410/harmonica/tests/test_sample_data.py#L35-L42

Feel free to add as many tests as you think, more tests is usually a good thing to have!

**Comment by nshea3** [comment]
Hi @santisoler, I have made the change you suggested, the `attrs` are now copied to a dictionary and set after the conversion. 

I have also added several tests for the presence of specific attributes: `refsysname`, `max_used_degree`, `modelname`, and `tide_system`.

I have not yet changed the netcdf files as discussed in #124. I started editing the files with the `netcdf4-python` library but I realized that the global attributes do not update as changes are made to the files, so the global attributes would be incorrect.

I am currently trying to regenerate the files from the ICGEM website (http://icgem.gfz-potsdam.de/calcgrid) without the repeated longitudes but the only output option is a `.gdf` file and I do not know how to convert that to a `.cdl` or `.nc` file?

**Comment by santisoler** [comment]
@nshea3 Sorry for stalling this PR for too long. I don't know why it kept under my radar for too long.
I'll merge right away if you agree.

We are planning a new Harmonica release for the next week(s). Thanks for the contribution!

**Pull request merged**
