### PR TITLE
Fix or disable some pylint complains after update

### PR DESCRIPTION
**Pull request by santisoler**
After a new update of `pylint`, it began to complain on extra issues. I solved
the ones that make more sense (using `.items()` when looping over a dictionary)
and disabled others locally and/or globally (like the obligation to use
f-strings and some `no-member` complains).

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
<whisper> let’s ditch pylint </whisper> 😛

**Comment by leouieda** [comment]
Seriously, though. Removing it and adding a bunch more flake8 plugins would make life a lot easier and remove all those comments turning off warnings in the code.

**Comment by santisoler** [comment]
Yes, totally agree that `pylint` needs to be replaced. Maybe we could keep it as a *second opinion tool*, but it's very demanding to keep all its complains satisfied.

**Comment by leouieda** [comment]
Sounds good to me 👍

**Pull request merged**
