### PR TITLE
Update versions of Sphinx and its plugins

### PR DESCRIPTION
**Pull request by santisoler**
Bump versions of Sphinx and its plugins in `environment.yml` and in `requirements-docs.txt`. Add CSS `dark-light` class to Harmonica logo in the `index.rst` to make its background transparent even in dark mode. Remove Harmonica logo in the left panel.

**Relevant issues/PRs:**

Similar changes to the ones applied in https://github.com/fatiando/choclo/pull/64

### CODE REVIEW

**Comment by santisoler** [comment]
With this version of Sphinx and the Book theme, we have dark theme in Harmonica docs. This introduced some issues regarding the rendering of output cells. The ones that show Pandas outputs are working after applying some CSS rules. But for xarray outputs things are harder.


Here are screen captures of light vs dark mode with xarray outputs:

Screenshot from 2024-03-12 15-09-10
Screenshot from 2024-03-12 15-09-20

**Comment by leouieda** [comment]
Yeah I noticed that. I think it'll just be a matter of time before xarray makes a fix to their CSS.

**Review by leouieda — APPROVED** [review]

**Comment by santisoler** [comment]
Just saw that Xarray's docs make use of Jupyter Books to build them and their HTML outputs look nice on dark theme: https://tutorial.xarray.dev/intermediate/xarray_ecosystem.html

**Comment by santisoler** [comment]
I'm merging this. We can take care of the Xarray inconsistency in another PR.

**Pull request merged**
