### PR TITLE
Drop null prisms when converting a prism layer to pyvista

### LINKED ISSUE #392: pyvista plot zero volumn
**Description of the problem:**

**Full code that generated the error**

```python
import numpy as np
import verde as vd
import harmonica as hm

# Build coordinates
# -----------------
# Build horizontal coordinates
easting = np.linspace(0, 300, 301)
northing = np.linspace(-100, 100, 101)
easting, northing = np.meshgrid(easting, northing)

# Define the top and bottom surfaces of the thin block
upward = easting * np.sin(-30) - 5
surface_top = easting * np.sin(np.radians(-30)) 
#shift the top surface by 50 elements (100*1 =100 m)
for i, row in enumerate(surface_top):
    surface_top[i, :] = np.concatenate((np.zeros(100), row[:-100]))
#shift the bottom surface by 30 elements (80*1 =80 m)
surface_bottom = easting * np.sin(np.radians(-30)) 
for i, row in enumerate(surface_bottom):
    surface_bottom[i, :] = np.concatenate((np.zeros(80), row[:-80]))

# Define density values (kg/m3)
# ---------------------
density_a, density_b, density_c = 2500, 2000, 2700
# Create density array for the prism layer
density_bottom = density_c * np.ones_like(surface_top)
density_block = density_b * np.ones_like(surface_top)
density_top = density_a * np.ones_like(surface_top)

# Create prism layer model
# ------------------------
model_block = hm.prism_layer(
    coordinates=(easting, northing),
    surface=surface_top,
    reference=surface_bottom,
    properties={"density": density_block},
)
model_bottom = hm.prism_layer(
    coordinates=(easting, northing),
    surface=surface_bottom ,
    reference= -200 * np.ones_like(surface_bottom),
    properties={"density": density_bottom},
)
model_top = hm.prism_layer(
    coordinates=(easting, northing),
    surface= 0 * np.ones_like(surface_top) ,
    reference= surface_top ,
    properties={"density": density_top},
)

# Plot using pyvista
# ------------------
# Try to import pyvista
try:
    import pyvista as pv
except ImportError:
    pv = None

# Plot only if pyvista is installed
if pv is not None:
   	plotter = pv.Plotter()
	plotter.add_mesh(model_block.prism_layer.to_pyvista(), scalars="density")
	plotter.add_mesh(model_top.prism_layer.to_pyvista(), scalars="density")
	plotter.add_mesh(model_bottom.prism_layer.to_pyvista(), scalars="density")
	plotter.show_axes()
	plotter.show() 
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: Ubunto
* Python installation (Anaconda, system, ETS):
* Version of Python: 3.10.6
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>Output of conda list</summary>
<pre>

PASTE OUTPUT OF CONDA LIST HERE

</pre>
</details>

### PR DESCRIPTION
**Pull request by santisoler**
Add an optional `drop_null_prisms` flag to the prism layer `to_pyvista()` method that ditches the prisms that have zero volume or `nan` values in their top or bottom boundaries. These null prisms won't be included in the PyVista Unstructured grid. By default the flag is set to `True`. Add a new test for this new feature.

**Relevant issues/PRs:**

Fixes #392

### CODE REVIEW

**Review by mdtanker — COMMENTED** [review]
This looks good and will definitely be helpful! One question. Why not drop null prisms by default? It shouldn't change the results, but it will avoid errors if you pass a prism layer with nan's. We could drop the `drop_null_prisms` argument altogether and just check the prism layer for nans at each call to `to_pyvista`. Happy with your implementation just curious about your thought process.

**Comment by santisoler** [comment]
> This looks good and will definitely be helpful! One question. Why not drop null prisms by default? It shouldn't change the results, but it will avoid errors if you pass a prism layer with nan's.

Thanks! I wasn't 100% sure about it. I was thinking mainly when plotting a topography, it might be weird to have a "hole" where the prism has a zero thickness. Now that I put it into words, it's weird to say that I'm actually plotting a prism that has no volume 😕 

> We could drop the `drop_null_prisms` argument altogether and just check the prism layer for nans at each call to `to_pyvista`. Happy with your implementation just curious about your thought process.

Sure! I totally forgot that the top and bottom arrays could have nans. We should totally remove those prisms too. I'll push a commit to fix that right away.

**Comment by santisoler** [comment]
What do you think @mdtanker? Should we set `drop_null_prisms=True` as default?

**Comment by mdtanker** [comment]
Those changes look good. I'd vote for `drop_null_prisms=True` by default. I just tried with a few grids and they look sort of strange with the null prisms included.

**Comment by mdtanker** [comment]
Looks good, merge away!

**Pull request merged**
